version: '3'

services: 
    web-srv:
        image: sysdevguru/coin-web-srv:v1.1
        depends_on: 
            - postgresql
        ports:
            - 8080:8080
        networks: 
            - coin_net
    rank-srv:
        image: sysdevguru/coin-rank-srv:v1.1
        depends_on: 
            - postgresql
        networks: 
            - coin_net
    price-srv:
        image: sysdevguru/coin-price-srv:v1.1
        depends_on: 
            - postgresql
        networks: 
            - coin_net
    postgresql:
        image: postgres:latest
        restart: always
        env_file: 
            - .env
        volumes:
            - ./scripts/db:/docker-entrypoint-initdb.d/
        networks: 
            - coin_net

networks: 
    coin_net:
